# These are supported funding model platforms for Mandelbrot Fractal Neural Synthesis & pCwOrM

# GitHub Sponsors username (activates native Sponsor button on GitHub)
github: [pCwOrM]

# Custom sponsorship, grant, and contribution links
custom:
  - https://github.com/pCwOrM/mandelbrot-fractal-neural-synthesis#-sponsor--grant-funding
  - https://answerr.me
